"""Metric

Revision ID: b5e4c8e21226
Revises: bccfe3439685
Create Date: 2024-04-02 18:06:51.418980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e4c8e21226'
down_revision = 'bccfe3439685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('forms_opened', sa.Integer(), nullable=False),
    sa.Column('forms_confirmed', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric')
    # ### end Alembic commands ###
